In [4]:
# NumPy Assignment

# 1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

import numpy as np
arr = np.arange(6)
print(arr)
print(arr.dtype)

[0 1 2 3 4 5]
int64


In [4]:
# 2. Given a NumPy array 'arr', check if its data type is float64.

arr = np.array([1.5, 2.6, 3.7])
print(arr.dtype)

float64


In [5]:
# 3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

arr = np.array([1+2j, 3+4j, 5+6j])
print(arr)
print(arr.dtype)

[1.+2.j 3.+4.j 5.+6.j]
complex128


In [6]:
# 4. Convert an existing NumPy array 'arr' of integers to float32 data type

arr = np.array([1,2,3,4,5])
arr_float = arr.astype(np.float32)
print(arr_float)
print(arr_float.dtype)

[1. 2. 3. 4. 5.]
float32


In [7]:
# 5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

arr = np.array([1.123456789, 2.987654321, 3.141592653])
arr_float= arr.astype(np.float32)
print(arr_float)
print(arr_float.dtype)


[1.1234568 2.9876542 3.1415927]
float32


In [8]:
# 6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type

def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape, size, dtype

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(array_attributes(arr))

((2, 3), 6, dtype('int64'))


In [9]:
# 7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality

def array_dimension(arr):
    return arr.ndim

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(array_dimension(arr))


2


In [10]:
# 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

def item_size_info(arr):
    item_size = arr.itemsize  
    total_size = arr.nbytes   
    return item_size, total_size

arr = np.array([[1, 2, 3], [4, 5, 6]])
item_size, total_size = item_size_info(arr)
print(f"Item Size: {item_size} bytes")
print(f"Total Size: {total_size} bytes")


Item Size: 8 bytes
Total Size: 48 bytes


In [11]:
# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

def array_strides(arr):
    return arr.strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(array_strides(arr))



(24, 8)


In [12]:
# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

def shape_stride(arr):
    shape = arr.shape      
    strides = arr.strides  
    return shape, strides

arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride(arr)
print(f"Shape: {shape}")
print(f"Strides: {strides}")


Shape: (2, 3)
Strides: (24, 8)


In [5]:
# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

def create_zeros_array(n):
    if n < 0:
        raise ValueError("The input n must be a non-negative integer.")
    return np.zeros(n)

n = 5
zeros_array = create_zeros_array(n)
print("Zero array with",n,"elements",zeros_array)

Zero array with 5 elements [0. 0. 0. 0. 0.]


In [6]:
# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.

def create_ones_matrix(rows, cols):
    if rows < 0 or cols < 0:
        raise ValueError("The number of rows and columns must be non-negative integers.")
    return np.ones((rows, cols))

rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)
print(f"Matrix of ones ({rows}x{cols}):\n", ones_matrix)


Matrix of ones (3x4):
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
# 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`

def generate_range_array(start, stop, step):
    if step == 0:
        raise ValueError("Step size must not be zero.")
    return np.arange(start, stop, step)

start = 0
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)
print(f"Range array from {start} to {stop} with step {step}:\n", range_array)

Range array from 0 to 10 with step 2:
 [0 2 4 6 8]


In [8]:
# 14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).

def generate_linear_space(start, stop, num):
    if num <= 0:
        raise ValueError("The number of points must be a positive integer.")
    return np.linspace(start, stop, num)

start = 1.0
stop = 10.0
num = 5
linear_space = generate_linear_space(start, stop, num)
print(f"{num} equally spaced values between {start} and {stop}:\n", linear_space)

5 equally spaced values between 1.0 and 10.0:
 [ 1.    3.25  5.5   7.75 10.  ]


In [9]:
# 15.Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.

def create_identity_matrix(n):
    if n < 0:
        raise ValueError("The size n must be a non-negative integer.")
    return np.eye(n)

n = 4
identity_matrix = create_identity_matrix(n)
print(f"Identity matrix of size {n}x{n}:\n", identity_matrix) 



Identity matrix of size 4x4:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [10]:
# 16. Write a function that takes a Python list and converts it into a NumPy array.

def convert_list_to_numpy_array(py_list):
    if not isinstance(py_list, list):
        raise TypeError("Input must be a Python list.")
    return np.array(py_list)

python_list = [1, 2, 3, 4, 5]
numpy_array = convert_list_to_numpy_array(python_list)
print("Python list:", python_list)
print("NumPy array:", numpy_array)  

Python list: [1, 2, 3, 4, 5]
NumPy array: [1 2 3 4 5]


In [11]:
# 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data

original_array = np.array([1, 2, 3, 4, 5])
print("Original array:", original_array)
view_array = original_array.view()
print("View array:", view_array)

view_array[0] = 10
print("\nAfter modifying the view array:")
print("Original array:", original_array)
print("View array:", view_array)

print("\nDo the original array and view share the same memory?")
print(original_array.base is None)  


Original array: [1 2 3 4 5]
View array: [1 2 3 4 5]

After modifying the view array:
Original array: [10  2  3  4  5]
View array: [10  2  3  4  5]

Do the original array and view share the same memory?
True


In [12]:
# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

def concatenate_arrays(array1, array2, axis=0):
    if not isinstance(array1, np.ndarray) or not isinstance(array2, np.ndarray):
        raise TypeError("Both inputs must be NumPy arrays.")
    
    try:
        return np.concatenate((array1, array2), axis=axis)
    except ValueError as e:
        raise ValueError(f"Concatenation failed: {e}")

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

concatenated_axis_0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:\n", concatenated_axis_0)

concatenated_axis_1 = concatenate_arrays(array1, array2, axis=1)
print("\nConcatenated along axis 1:\n", concatenated_axis_1)


Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [13]:
# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5], [6]])

print("Array 1:\n", array1)
print("\nArray 2:\n", array2)

concatenated_array = np.concatenate((array1, array2), axis=1)
print("\nConcatenated array (horizontally):\n", concatenated_array)


Array 1:
 [[1 2]
 [3 4]]

Array 2:
 [[5]
 [6]]

Concatenated array (horizontally):
 [[1 2 5]
 [3 4 6]]


In [14]:
# 20. Write a function that vertically stacks multiple NumPy arrays given as a list.

def vertical_stack_arrays(arrays):
    if not all(isinstance(arr, np.ndarray) for arr in arrays):
        raise TypeError("All elements in the list must be NumPy arrays.")
    
    try:
        return np.vstack(arrays)
    except ValueError as e:
        raise ValueError(f"Vertical stacking failed: {e}")

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6]])
array3 = np.array([[7, 8]])

stacked_array = vertical_stack_arrays([array1, array2, array3])
print("Vertically stacked array:\n", stacked_array)


Vertically stacked array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [15]:
# 21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size

import numpy as np

def create_range_array(start, stop, step):
    if step == 0:
        raise ValueError("Step size must be non-zero.")
    if start > stop and step > 0:
        raise ValueError("For a positive step, start should not be greater than stop.")
    if start < stop and step < 0:
        raise ValueError("For a negative step, start should not be less than stop.")
    
    return np.arange(start, stop + 1, step)

start = 5
stop = 15
step = 2
range_array = create_range_array(start, stop, step)
print(f"Array of integers from {start} to {stop} with step size {step}:\n", range_array)


Array of integers from 5 to 15 with step size 2:
 [ 5  7  9 11 13 15]


In [16]:
# 22.Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

def generate_equally_spaced_values():
    return np.linspace(0, 1, 10)

equally_spaced_values = generate_equally_spaced_values()
print("Equally spaced values between 0 and 1 (inclusive):\n", equally_spaced_values)


Equally spaced values between 0 and 1 (inclusive):
 [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [17]:
# 23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

def generate_logarithmically_spaced_values():
    return np.logspace(0, 3, 5, base=10)

log_spaced_values = generate_logarithmically_spaced_values()
print("Logarithmically spaced values between 1 and 1000 (inclusive):\n", log_spaced_values)


Logarithmically spaced values between 1 and 1000 (inclusive):
 [   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [18]:
# 24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

import numpy as np
import pandas as pd

def create_dataframe():
    data = np.random.randint(1, 101, size=(5, 3))
    
    df = pd.DataFrame(data, columns=["A", "B", "C"])
    
    return df
    
df = create_dataframe()
print("Pandas DataFrame with random integers:\n", df)


Pandas DataFrame with random integers:
     A   B   C
0  32  35  54
1   4  90  57
2  72  46  79
3  29  70  15
4  15   9  56


In [19]:
# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

def replace_negatives_with_zero(df, column):
    df[column] = np.where(df[column] < 0, 0, df[column])
    return df

data = {
    'A': [10, -5, 15, -3, 7],
    'B': [2, -8, 5, -6, 9],
    'C': [-1, 4, -2, 3, 6]
}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

df = replace_negatives_with_zero(df, 'A')

print("\nUpdated DataFrame (after replacing negatives in 'A' with zeros):")
print(df)


Original DataFrame:
    A  B  C
0  10  2 -1
1  -5 -8  4
2  15  5 -2
3  -3 -6  3
4   7  9  6

Updated DataFrame (after replacing negatives in 'A' with zeros):
    A  B  C
0  10  2 -1
1   0 -8  4
2  15  5 -2
3   0 -6  3
4   7  9  6


In [20]:
# 26. Access the 3rd element from the given NumPy array
arr = np.array([10, 20, 30, 40, 50])

third_element = arr[2]

print("The 3rd element in the array is:", third_element)

The 3rd element in the array is: 30


In [21]:
# 27. Retrieve the element at index (1, 2) from the 2D NumPy array

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

element = arr_2d[1, 2]

print("The element at index (1, 2) is:", element)


The element at index (1, 2) is: 6


In [22]:
# 28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.

arr = np.array([3, 8, 2, 10, 5, 7])
elements_greater_than_5 = arr[arr > 5]

print("Elements greater than 5:", elements_greater_than_5)

Elements greater than 5: [ 8 10  7]


In [23]:
# 29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
sliced_arr = arr[2:6]

print("Sliced elements from index 2 to 5:", sliced_arr)

Sliced elements from index 2 to 5: [3 4 5 6]


In [24]:
# 30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

sub_array = arr_2d[1:3, 1:3]

print("Extracted sub-array:\n", sub_array)

Extracted sub-array:
 [[5 6]
 [8 9]]


In [25]:
# 31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.

def extract_elements_by_indices(arr_2d, indices):
    extracted_elements = arr_2d[indices[:, 0], indices[:, 1]]
    
    return extracted_elements

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

indices = np.array([[0, 1], [1, 2], [2, 0]])

result = extract_elements_by_indices(arr_2d, indices)
print("Extracted elements:", result)


Extracted elements: [2 6 7]


In [26]:
# 32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

def filter_elements_by_threshold(arr, threshold):
    filtered_elements = arr[arr > threshold]
    return filtered_elements

arr = np.array([3, 8, 2, 10, 5, 7])
threshold = 5

result = filter_elements_by_threshold(arr, threshold)
print("Filtered elements greater than threshold:", result)


Filtered elements greater than threshold: [ 8 10  7]


In [27]:
# 33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

def extract_elements_from_3d_array(arr_3d, row_indices, col_indices, depth_indices):
  
    extracted_elements = arr_3d[row_indices, col_indices, depth_indices]
    return extracted_elements

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                   [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                   [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])

row_indices = np.array([0, 1, 2])  
col_indices = np.array([1, 0, 2])  
depth_indices = np.array([2, 1, 0])  

result = extract_elements_from_3d_array(arr_3d, row_indices, col_indices, depth_indices)
print("Extracted elements:", result)


Extracted elements: [ 6 11 25]


In [ ]:
# 34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.

def filter_elements_by_conditions(arr, condition1, condition2):
    filtered_elements = arr[condition1 & condition2]
    return filtered_elements

arr = np.array([3, 8, 2, 10, 5, 7])


condition1 = arr > 5  
condition2 = arr % 2 == 0  

result = filter_elements_by_conditions(arr, condition1, condition2)
print("Filtered elements:", result)


Filtered elements: [ 8 10]


In [29]:
# 35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

def extract_elements_using_indices(arr_2d, row_indices, col_indices):
    
    extracted_elements = arr_2d[row_indices, col_indices]
    
    return extracted_elements

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_indices = np.array([0, 1, 2])  
col_indices = np.array([1, 0, 2])  

result = extract_elements_using_indices(arr_2d, row_indices, col_indices)
print("Extracted elements:", result)


Extracted elements: [2 4 9]


In [30]:
# 36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

result = arr + 5

print("Array after adding 5 to each element:\n", result)


Array after adding 5 to each element:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [32]:
# 37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

arr1 = np.array([[1, 2, 3]])  
arr2 = np.array([[4, 5, 6, 7],
                 [8, 9, 10, 11],
                 [12, 13, 14, 15]])  
arr1_reshaped = arr1.T
result = arr2 * arr1_reshaped

print("Result of multiplication using broadcasting:\n", result)


Result of multiplication using broadcasting:
 [[ 4  5  6  7]
 [16 18 20 22]
 [36 39 42 45]]


In [33]:
# 38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

arr1 = np.array([[1, 2, 3, 4]])  
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])  

result = arr2 + arr1.T 

print("Result of addition using broadcasting:\n", result)


Result of addition using broadcasting:
 [[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


In [34]:
# 39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

arr1 = np.array([[1], [2], [3]])  
arr2 = np.array([[4, 5, 6]])       

result = arr1 + arr2

print("Result of addition using broadcasting:\n", result)

Result of addition using broadcasting:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [35]:
# 40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

arr1 = np.array([[1, 2, 3], [4, 5, 6]])  
arr2 = np.array([[7, 8], [9, 10]])        

arr2_broadcasted = arr2[:, :, np.newaxis] 
arr2_broadcasted = np.repeat(arr2_broadcasted, 3, axis=2)  

result = arr1 * arr2_broadcasted

print("Result of multiplication using broadcasting:\n", result)

Result of multiplication using broadcasting:
 [[[ 7 14 21]
  [32 40 48]]

 [[ 9 18 27]
  [40 50 60]]]


In [36]:
# 41. Calculate column wise mean for the given array:

arr = np.array([[1, 2, 3], [4, 5, 6]])

column_wise_mean = np.mean(arr, axis=0)

print("Column-wise mean:", column_wise_mean)


Column-wise mean: [2.5 3.5 4.5]


In [37]:
# 42. Find maximum value in each row of the given array:

arr = np.array([[1, 2, 3], [4, 5, 6]])

row_max = np.amax(arr, axis=1)

print("Maximum value in each row:", row_max)

Maximum value in each row: [3 6]


In [38]:
# 43. For the given array, find indices of maximum value in each column

arr = np.array([[1, 2, 3], [4, 5, 6]])

column_max_indices = np.argmax(arr, axis=0)

print("Indices of maximum value in each column:", column_max_indices)


Indices of maximum value in each column: [1 1 1]


In [39]:
# 44. For the given array, apply custom function to calculate moving sum along rows

arr = np.array([[1, 2, 3], [4, 5, 6]])

def moving_sum(arr, window_size):
    return np.convolve(arr, np.ones(window_size), mode='valid')

result = np.apply_along_axis(moving_sum, axis=1, arr=arr, window_size=2)

print("Moving sum along rows:", result)

Moving sum along rows: [[ 3.  5.]
 [ 9. 11.]]


In [40]:
# 45. In the given array, check if all elements in each column are even.

arr = np.array([[2, 4, 6], [3, 5, 7]])

result = np.all(arr % 2 == 0, axis=0)

print("Are all elements in each column even?", result)


Are all elements in each column even? [False False False]


In [41]:
# 46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.

original_array = np.array([1, 2, 3, 4, 5, 6])

m, n = 2, 3  

reshaped_matrix = original_array.reshape(m, n)

print("Reshaped matrix:\n", reshaped_matrix)

Reshaped matrix:
 [[1 2 3]
 [4 5 6]]


In [42]:
# 47. Create a function that takes a matrix as input and returns the flattened array.

def flatten_matrix(matrix):
    return matrix.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

flattened_array = flatten_matrix(input_matrix)

print("Flattened array:", flattened_array)

Flattened array: [1 2 3 4 5 6]


In [43]:
# 48. Write a function that concatenates two given arrays along a specified axis

def concatenate_arrays(array1, array2, axis):
    return np.concatenate((array1, array2), axis=axis)

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

result_axis_0 = concatenate_arrays(array1, array2, axis=0)

result_axis_1 = concatenate_arrays(array1, array2, axis=1)

print("Concatenated along axis 0:\n", result_axis_0)
print("Concatenated along axis 1:\n", result_axis_1)



Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [44]:
# 49. Create a function that splits an array into multiple sub-arrays along a specified axis.

def split_array(array, axis, num_splits):
    return np.split(array, num_splits, axis=axis)

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

result_axis_0 = split_array(original_array, axis=0, num_splits=3)

result_axis_1 = split_array(original_array, axis=1, num_splits=3)

print("Split along axis 0 (rows):", result_axis_0)
print("Split along axis 1 (columns):", result_axis_1)

Split along axis 0 (rows): [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
Split along axis 1 (columns): [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [45]:
# 50. Write a function that inserts and then deletes elements from a given array at specified indices.

def insert_and_delete(array, indices_to_insert, values_to_insert, indices_to_delete):
    array = np.insert(array, indices_to_insert, values_to_insert)
    
    array = np.delete(array, indices_to_delete)
    
    return array

original_array = np.array([1, 2, 3, 4, 5])

indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

result = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)

print("Array after insertion and deletion:", result)


Array after insertion and deletion: [ 1 10  4 11  5]


In [46]:
# 51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.Perform element-wise addition between `arr1` and `arr2`.

arr1 = np.random.randint(1, 11, size=5)

arr2 = np.arange(1, 11)

result = arr1 + arr2[:5]  

print("arr1:", arr1)
print("arr2:", arr2[:5])  
print("Element-wise addition result:", result)

arr1: [ 5  3  8  8 10]
arr2: [1 2 3 4 5]
Element-wise addition result: [ 6  5 11 12 15]


In [47]:
# 52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

arr1 = np.arange(10, 0, -1)

arr2 = np.arange(1, 11)

result = arr1 - arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise subtraction result:", result)

arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Element-wise subtraction result: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [48]:
# 53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

arr1 = np.random.randint(1, 11, size=5)

arr2 = np.array([1, 2, 3, 4, 5])

result = arr1 * arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise multiplication result:", result)

arr1: [10  8  8  3 10]
arr2: [1 2 3 4 5]
Element-wise multiplication result: [10 16 24 12 50]


In [49]:
# 54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

arr1 = np.array([2, 4, 6, 8, 10])

arr2 = np.array([1, 2, 3, 4, 5])

result = arr1 / arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Element-wise division result:", result)

arr1: [ 2  4  6  8 10]
arr2: [1 2 3 4 5]
Element-wise division result: [2. 2. 2. 2. 2.]


In [50]:
# 55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise

arr1 = np.array([1, 2, 3, 4, 5])

arr2 = np.array([5, 4, 3, 2, 1])

result = arr1 ** arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Exponentiation result:", result)

arr1: [1 2 3 4 5]
arr2: [5 4 3 2 1]
Exponentiation result: [ 1 16 27 16  5]


In [51]:
# 56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings

def count_substring_occurrences(arr, substring):
    occurrences = np.char.find(arr, substring) != -1  
    return np.sum(occurrences)  
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'

count = count_substring_occurrences(arr, substring)
print(f"The substring '{substring}' occurs {count} times in the array.")


The substring 'hello' occurs 3 times in the array.


In [52]:
# 57. Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

def extract_uppercase(arr):
    uppercase_chars = np.array([ ''.join([char for char in string if char.isupper()]) for string in arr])
    return uppercase_chars

result = extract_uppercase(arr)
print("Uppercase characters extracted:", result)


Uppercase characters extracted: ['H' 'W' 'OAI' 'GPT']


In [53]:
# 58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

def replace_substring(arr, old_substring, new_substring):
    return np.char.replace(arr, old_substring, new_substring)

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'apple'
new_substring = 'fruit'

result = replace_substring(arr, old_substring, new_substring)
print("Array after replacement:", result)

Array after replacement: ['fruit' 'banana' 'grape' 'pinefruit']


In [54]:
# 59. Write a function that concatenates strings in a NumPy array element-wise.

def concatenate_strings(arr1, arr2):
    return np.char.add(arr1, arr2)

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

result = concatenate_strings(arr1, arr2)
print("Concatenated result:", result)

Concatenated result: ['HelloOpen' 'WorldAI']


In [55]:
# 60. Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

def longest_string_length(arr):
    
    lengths = np.char.str_len(arr)
   
    return np.max(lengths)


result = longest_string_length(arr)
print("Length of the longest string:", result)

Length of the longest string: 9


In [56]:
# 61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

dataset = np.random.randint(1, 1001, size=100)

mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset)

print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Variance: {variance}")
print(f"Standard Deviation: {std_deviation}")

Mean: 456.8
Median: 402.5
Variance: 83578.3
Standard Deviation: 289.09911795092006


In [57]:
# 62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

random_array = np.random.randint(1, 101, size=50)

percentile_25 = np.percentile(random_array, 25)
percentile_75 = np.percentile(random_array, 75)

print(f"25th Percentile: {percentile_25}")
print(f"75th Percentile: {percentile_75}")

25th Percentile: 23.0
75th Percentile: 74.0


In [58]:
# 63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

correlation_matrix = np.corrcoef(arr1, arr2)

correlation_coefficient = correlation_matrix[0, 1]

print(f"Correlation Coefficient: {correlation_coefficient}")

Correlation Coefficient: -0.9999999999999999


In [59]:
# 64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.

matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

result = np.dot(matrix1, matrix2)

print("Result of matrix multiplication:\n", result)

Result of matrix multiplication:
 [[19 22]
 [43 50]]


In [60]:
# 65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

random_array = np.random.randint(10, 1001, size=50)

percentile_10 = np.percentile(random_array, 10)
percentile_50 = np.percentile(random_array, 50)  
percentile_90 = np.percentile(random_array, 90)

first_quartile = np.percentile(random_array, 25)
third_quartile = np.percentile(random_array, 75)

print(f"10th Percentile: {percentile_10}")
print(f"50th Percentile (Median): {percentile_50}")
print(f"90th Percentile: {percentile_90}")
print(f"First Quartile (25th Percentile): {first_quartile}")
print(f"Third Quartile (75th Percentile): {third_quartile}")

10th Percentile: 158.0
50th Percentile (Median): 584.0
90th Percentile: 929.2
First Quartile (25th Percentile): 267.25
Third Quartile (75th Percentile): 802.75


In [61]:
# 66. Create a NumPy array of integers and find the index of a specific element.

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

element_to_find = 50

index_of_element = np.where(arr == element_to_find)[0][0]

print(f"The index of element {element_to_find} is: {index_of_element}")

The index of element 50 is: 4


In [62]:
# 67. Generate a random NumPy array and sort it in ascending order

random_array = np.random.randint(1, 101, size=10)

sorted_array = np.sort(random_array)

print("Original Array:", random_array)
print("Sorted Array in Ascending Order:", sorted_array)

Original Array: [74 31 47 53 29 48 83 34 99 75]
Sorted Array in Ascending Order: [29 31 34 47 48 53 74 75 83 99]


In [63]:
# 68. Filter elements >20  in the given NumPy array.

arr = np.array([12, 25, 6, 42, 8, 30])

filtered_elements = arr[arr > 20]

print("Elements greater than 20:", filtered_elements)

Elements greater than 20: [25 42 30]


In [64]:
# 69. Filter elements which are divisible by 3 from a given NumPy array.

arr = np.array([1, 5, 8, 12, 15])

divisible_by_3 = arr[arr % 3 == 0]

print("Elements divisible by 3:", divisible_by_3)

Elements divisible by 3: [12 15]


In [65]:
# 70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.

arr = np.array([10, 20, 30, 40, 50])

filtered_elements = arr[(arr >= 20) & (arr <= 40)]

print("Elements ≥ 20 and ≤ 40:", filtered_elements)

Elements ≥ 20 and ≤ 40: [20 30 40]


In [2]:
# 71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

import numpy as np
arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder

if byte_order == '=':
    print("Byte order: Native (matches system's endianness)")
elif byte_order == '<':
    print("Byte order: Little-endian")
elif byte_order == '>':
    print("Byte order: Big-endian")
else:
    print(f"Byte order: Unknown ({byte_order})")

Byte order: Native (matches system's endianness)


In [3]:
# 72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)
arr.byteswap(inplace=True)

print("Array after byte swapping:")
print(arr)

Array after byte swapping:
[16777216 33554432 50331648]


In [6]:
# 73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)
swapped_arr = arr.view(arr.dtype.newbyteorder())

print("Original array:")
print(arr)

print("Array with swapped byte order:")
print(swapped_arr)

Original array:
[1 2 3]
Array with swapped byte order:
[16777216 33554432 50331648]


In [7]:
# 74. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.

arr = np.array([1, 2, 3], dtype=np.int32)
system_endianness = arr.dtype.byteorder

if system_endianness == '=':  
    import sys
    if sys.byteorder == 'little':
        print("System endianness is Little-endian.")
    else:
        print("System endianness is Big-endian.")
    swapped_arr = arr.view(arr.dtype.newbyteorder())
else:
    print("Array byte order is not native. Swapping byte order.")
    swapped_arr = arr.view(arr.dtype.newbyteorder())

print("Original array:")
print(arr)

print("Array with swapped byte order:")
print(swapped_arr)


System endianness is Little-endian.
Original array:
[1 2 3]
Array with swapped byte order:
[16777216 33554432 50331648]


In [8]:
# 75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.

arr = np.array([1, 2, 3], dtype=np.int32)
byte_order = arr.dtype.byteorder

if byte_order == '=': 
    print("No byte swapping is necessary. ")
elif (byte_order == '<' and np.little_endian) or (byte_order == '>' and not np.little_endian):
    print("No byte swapping is necessary. The array is already in the correct byte order.")
else:
    print("Byte swapping is necessary. ")


No byte swapping is necessary. 


In [9]:
# 76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

arr1 = np.arange(1, 11)

copy_arr = arr1.copy()

copy_arr[0] = 100

print("Original array (arr1):")
print(arr1)

print("Modified copy (copy_arr):")
print(copy_arr)

if np.array_equal(arr1, copy_arr):
    print("Modifying copy_arr affects arr1.")
else:
    print("Modifying copy_arr does not affect arr1.")

Original array (arr1):
[ 1  2  3  4  5  6  7  8  9 10]
Modified copy (copy_arr):
[100   2   3   4   5   6   7   8   9  10]
Modifying copy_arr does not affect arr1.


In [10]:
# 77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

matrix = np.random.randint(0, 100, size=(3, 3))

view_slice = matrix[1:, 1:]

view_slice[0, 0] = -1

print("Original matrix after modification:")
print(matrix)

print("Modified view_slice:")
print(view_slice)

if matrix[1, 1] == view_slice[0, 0]:
    print("Modifying view_slice affects the original matrix.")
else:
    print("Modifying view_slice does not affect the original matrix.")

Original matrix after modification:
[[48 73 34]
 [10 -1 79]
 [75 49 65]]
Modified view_slice:
[[-1 79]
 [49 65]]
Modifying view_slice affects the original matrix.


In [11]:
# 78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

array_a = np.arange(1, 13).reshape(4, 3)

view_b = array_a[1:3, :]

view_b += 5

print("Original array (array_a) after modification:")
print(array_a)

print("Modified view (view_b):")
print(view_b)

if np.array_equal(array_a[1:3, :], view_b):
    print("Broadcasting on view_b alters the original array (array_a).")
else:
    print("Broadcasting on view_b does not alter the original array (array_a).")

Original array (array_a) after modification:
[[ 1  2  3]
 [ 9 10 11]
 [12 13 14]
 [10 11 12]]
Modified view (view_b):
[[ 9 10 11]
 [12 13 14]]
Broadcasting on view_b alters the original array (array_a).


In [12]:
# 79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

orig_array = np.arange(1, 9).reshape(2, 4)

reshaped_view = orig_array.reshape(4, 2)

reshaped_view[0, 1] = 100

print("Original array (orig_array) after modification:")
print(orig_array)

print("Modified reshaped view (reshaped_view):")
print(reshaped_view)

if np.array_equal(orig_array, reshaped_view.reshape(2, 4)):
    print("Modifying reshaped_view affects the original array (orig_array).")
else:
    print("Modifying reshaped_view does not affect the original array (orig_array).")

Original array (orig_array) after modification:
[[  1 100   3   4]
 [  5   6   7   8]]
Modified reshaped view (reshaped_view):
[[  1 100]
 [  3   4]
 [  5   6]
 [  7   8]]
Modifying reshaped_view affects the original array (orig_array).


In [13]:
# 80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

data = np.random.randint(1, 11, size=(3, 4))

data_copy = data[data > 5].copy()

data_copy[0] = 100

print("Original data array:")
print(data)

print("Modified data_copy:")
print(data_copy)

if np.array_equal(data, data_copy):
    print("Modifying data_copy affects the original data.")
else:
    print("Modifying data_copy does not affect the original data.")

Original data array:
[[ 1  4  6  6]
 [ 1  7  1  7]
 [ 7 10  4  6]]
Modified data_copy:
[100   6   7   7   7  10   6]
Modifying data_copy does not affect the original data.


In [14]:
# 81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them

A = np.random.randint(1, 11, size=(3, 3))
B = np.random.randint(1, 11, size=(3, 3))

C_add = A + B  
C_sub = A - B  

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nMatrix A + Matrix B:")
print(C_add)

print("\nMatrix A - Matrix B:")
print(C_sub)

Matrix A:
[[2 8 2]
 [3 7 4]
 [2 8 4]]

Matrix B:
[[2 8 4]
 [7 4 1]
 [2 4 5]]

Matrix A + Matrix B:
[[ 4 16  6]
 [10 11  5]
 [ 4 12  9]]

Matrix A - Matrix B:
[[ 0  0 -2]
 [-4  3  3]
 [ 0  4 -1]]


In [15]:
# 82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

C = np.random.randint(1, 11, size=(3, 2))
D = np.random.randint(1, 11, size=(2, 4))

result = np.dot(C, D)

print("Matrix C (3x2):")
print(C)

print("\nMatrix D (2x4):")
print(D)

print("\nMatrix multiplication result (C @ D):")
print(result)

Matrix C (3x2):
[[7 4]
 [2 2]
 [3 8]]

Matrix D (2x4):
[[6 6 1 5]
 [7 9 6 8]]

Matrix multiplication result (C @ D):
[[70 78 31 67]
 [26 30 14 26]
 [74 90 51 79]]


In [16]:
# 83. Create a matrix `E` and find its transpose.

E = np.random.randint(1, 11, size=(3, 4))

E_transpose = E.T

print("Matrix E:")
print(E)

print("\nTranspose of Matrix E:")
print(E_transpose)

Matrix E:
[[ 1 10  2 10]
 [ 3  5  4  4]
 [ 4  8  1  7]]

Transpose of Matrix E:
[[ 1  3  4]
 [10  5  8]
 [ 2  4  1]
 [10  4  7]]


In [17]:
# 84. Generate a square matrix `F` and compute its determinant.

F = np.random.randint(1, 11, size=(3, 3))

det_F = np.linalg.det(F)

print("Matrix F:")
print(F)

print("\nDeterminant of matrix F:")
print(det_F)

Matrix F:
[[2 6 2]
 [8 5 5]
 [9 6 6]]

Determinant of matrix F:
-12.0


In [18]:
# 85. Create a square matrix `G` and find its inverse.

G = np.random.randint(1, 11, size=(3, 3))

det_G = np.linalg.det(G)

if det_G != 0:
    G_inverse = np.linalg.inv(G)
   
    print("Matrix G:")
    print(G)

    print("\nInverse of matrix G:")
    print(G_inverse)
else:
    print("Matrix G is not invertible (determinant is zero).")

Matrix G:
[[6 1 9]
 [3 5 3]
 [2 8 9]]

Inverse of matrix G:
[[ 0.09090909  0.27272727 -0.18181818]
 [-0.09090909  0.15584416  0.03896104]
 [ 0.06060606 -0.1991342   0.11688312]]
